### ISSUE TITLE
Fix neat-omega dependency

### ISSUE THREAD

**Issue by JBCSU** [SU-SWS/decanter#24] opened 2017-03-01 22:29 UTC
Now that decanter is integrated into homesite, neat-omega is not being installed in a location where sass can find its files. The work around is to add `"neat-omega": "github:kgcreative/neat-omega"` as a dev dependency in homesite's package.json.

**Comment by sherakama** [comment] 2017-03-07 18:31
Can you provide the package.json file that is producing this irregularity? I am unable to reproduce locally.

**Comment by JBCSU** [comment] 2017-03-07 19:02
@kgcreative may have fixed this, but yeah, sure, here's the `package.json` as it exists today. It may be slightly different from when I first reported the problem.

```javascript
{
  "name": "homesite17",
  "version": "1.0.0",
  "description": "Homesite 2017 build process",
  "license": "GPL-3.0",
  "repository": "repo1",
  "_themepath": "wp-content/themes/homesite17",
  "_npmpath": "dev/node_modules",
  "_componentpath": "dev/dev_components",
  "_deploypath": "dev/deploy",
  "_dev_git_repo": "repo2",
  "_wpe_staging_repo": "repo3",
  "_wpe_production_repo": "repo4",
  "_aws_repo": "repo5",
  "engines": {
    "node": "5.11.0",
    "npm": "3.8.6"
  },
  "dependencies": {
    "jquery": "^3.1.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "browser-sync": "^2.18.7",
    "decanter": "github:SU-SWS/decanter.git#8d683f7b42a83652c61f8d90ddc5e19762c45692",
    "neat-omega": "^2.0.7",
    "glob": "^7.1.1",
    "grunt": "^1.0.1",
    "grunt-auto-install": "^0.3.1",
    "grunt-browser-sync": "^2.1.3",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-clean": "~1.0.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^1.0.2",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "~1.0.0",
    "grunt-git": "^1.0.3",
    "grunt-header": "^1.0.0",
    "grunt-php-set-constant": "0.0.15",
    "grunt-postcss": "^0.8.0",
    "grunt-preprocess": "^5.1.0",
    "grunt-sass": "^2.0.0",
    "grunt-update-submodules": "^0.4.1",
    "grunt-webpack": "^2.0.1",
    "load-grunt-tasks": "^3.5.2",
    "verge": "^1.9.1",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0"
  },
  "browserslist": [
    "> 1%",
    "last 3 versions",
    "ie 9"
  ]
}
```

**Comment by kgcreative** [comment] 2017-03-09 02:52
@JBCSU - I've released `neat-omega` as an NPM package, so hopefully decanter now properly pulls it in where it's supposed to. The issue seemed to be unique to your setup, so at some point when we have time, let's test removing `neat-omega` from the homesite `package.json` to see if it works, and if so, we can close this PR.

**Closed** 2017-03-15 18:13 UTC
